[SeasonHUD]
	#Enable the mod?
	#(true/false)
	#Default is true.
	enable_mod = true

	[SeasonHUD.Season]
		#Show the Tropical season (Wet/Dry) while in Tropical Biomes.
		#This will not change the season behavior in the biomes, just
		#what is displayed on the Hud
		#(true/false)
		#Default is true.
		enable_show_tropical_season = true
		#Show sub-season instead of the basic season?
		#i.e. Early Winter, Mid Autumn, Late Spring
		#(true/false)
		#
		#If using Fabric Seasons:
		#You will want to change the 'seasonLength' options in the
		#Fabric Seasons config (seasons.json) to be divisible by 3
		#It defaults to 672000 ticks (28 days)
		#
		#Default is false.
		enable_show_sub_season = true
		#Show the current day of the season/sub-season?
		#Default is SHOW_DAY.
		#Allowed Values: NONE, SHOW_DAY, SHOW_WITH_TOTAL_DAYS
		enable_show_day = "SHOW_DAY"
		#Show the current fertility of the biome?
		#Only shows if not the default fertility of the season
		#Default is false.
		enable_show_fertility = false
		#If the season name should be replaced with the fertility
		#value when it differs from the default of the biome
		#Default is false.
		enable_fertility_replaces_season = false

	[SeasonHUD.Minimap]
		#Enable integration with minimap mods?
		#(true/false)
		#Default is true.
		enable_minimap_integration = true
		#Show the default SeasonHUD when the minimap is hidden?
		#(true/false)
		#Default is false.
		enable_show_minimap_hidden = false
