name = "Monkey Modpack"
author = "Just Mango"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6966380319d9d356ba2605532f9bd740371f00adbd5de7f5f7a2dedbef197aab"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
