name = "Monkey Modpack"
author = "Just Mango"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f811cf58a18bb5f5fdb38e039d797303127b200f2c4da00b63df21e5b051914"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
