name = "Monkey Modpack"
author = "Just Mango"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78f0e53672764059b8f53989c6a54c5cc977aaca7bf746387ddd0222d0c37aab"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
